### PR TITLE
A01638032-homework-02

### PR DESCRIPTION
**Pull request by Marcoalpz**

### CODE REVIEW

**Comment by VictorRodriguez** [comment]
When I run this i get 

➜  parallel-programming-lecture git:(pullrequest) ✗ ./milk
Hello world

but nothing else

**Comment by Marcoalpz** [comment]
My mistake. Only upload 1 file and I was missing another. Sorry I don't know how to use github very well

**Comment by Marcoalpz** [comment]
Can I send the other file to your email?

**Comment by VictorRodriguez** [comment]
Please paste here if you prefer

**Comment by Marcoalpz** [comment]
/*
Program that create de milk seller server
Marco Alexis López Cruz
A01638032
13/11/2021
*/
#include <stdlib.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <stdio.h>
#include <semaphore.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>

#define SHM_SIZE 1024 // 1K of shared memory segment

char sem_name[] = "Marco";
sem_t *semaphore;
int shmid;        // Shared memory segment
int *num_bottles; // Number of bottles
char *shm;        // Virtual memory
key_t key = 1000; // Shared memory segment name
int *client_command; /* Client command */

// Create a semaphore object 
void create_semaphore(){
    semaphore = sem_open(sem_name, O_CREAT, 0644, 1); //Open semaphore with Oflags
    if (semaphore == SEM_FAILED){
        perror("Unable to create semaphore"); // Print error value
        sem_unlink(sem_name);                 // Remove named semaphore name
        exit(-1);                             // Finish with error
    }
}

//Create a shared memory object
void create_shared_memory(){
    shmid = shmget(key, SHM_SIZE, IPC_CREAT | 0666); //create the shared memory segment with this key
    if (shmid < 0){
        perror("failure in shmget"); // Print error value
        exit(-1);                    // Finish with error
    }
}

int main(){
    create_semaphore(); // Initialize the semaphore

    create_shared_memory(); // Create shared memory

    shm = shmat(shmid, NULL, 0); //Attach segment to virtual memory

    num_bottles = shm; // Write into memory

    *num_bottles = 1000; // Assign 1000 bottles to the factory

    while (*shm != '*'){
        printf("%d bottles available\n", *num_bottles);
        sleep(1);
    }

    sem_close(semaphore);
    sem_unlink(sem_name);
    shmctl(shmid, IPC_RMID, 0);
    _exit(0);

    return 0;
}

**Comment by Marcoalpz** [comment]
/*
Program that create de milk seller server
Marco Alexis López Cruz
A01638032
13/11/2021
*/
#include <stdlib.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <stdio.h>
#include <semaphore.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>

#define SHM_SIZE 1024 // 1K of shared memory segment

char sem_name[] = "Marco";
sem_t *semaphore;
int shmid;        // Shared memory segment
int *num_bottles; // Number of bottles
char *shm;        // Virtual memory
key_t key = 1000; // Shared memory segment name
int *client_command; /* Client command */

// Create a semaphore object 
void create_semaphore(){
    semaphore = sem_open(sem_name, O_CREAT, 0644, 1); //Open semaphore with Oflags
    if (semaphore == SEM_FAILED){
        perror("Unable to create semaphore"); // Print error value
        sem_unlink(sem_name);                 // Remove named semaphore name
        exit(-1);                             // Finish with error
    }
}

//Create a shared memory object
void create_shared_memory(){
    shmid = shmget(key, SHM_SIZE, IPC_CREAT | 0666); //create the shared memory segment with this key
    if (shmid < 0){
        perror("failure in shmget"); // Print error value
        exit(-1);                    // Finish with error
    }
}

int main(){
    create_semaphore(); // Initialize the semaphore

    create_shared_memory(); // Create shared memory

    shm = shmat(shmid, NULL, 0); //Attach segment to virtual memory

    num_bottles = shm; // Write into memory

    *num_bottles = 1000; // Assign 1000 bottles to the factory

    while (*shm != '*'){
        printf("%d bottles available\n", *num_bottles);
        sleep(1);
    }

    sem_close(semaphore);
    sem_unlink(sem_name);
    shmctl(shmid, IPC_RMID, 0);
    _exit(0);

    return 0;
}

**Comment by Marcoalpz** [comment]
By the way. I sent you an email about homework 03, I don't know if you were able to review it or did you get the mail

**Pull request closed without merging**
