### PR TITLE
A00827629-Homework-02

### PR DESCRIPTION
**Pull request by Juan-Carlos-TV**
Directorio
./Labs/06/

Programas:
 labs/06/milk-client-A00827629.c
 labs/06/milk-server-A00827629.c

### CODE REVIEW

**Comment by VictorRodriguez** [comment]
$ ./server
reader:unable to execute semaphore: No such file or directory
$ ./milk-client-A00827629
reader:unable to execute semaphore: No such file or directory

**Comment by Juan-Carlos-TV** [comment]
That's weird. I'm the one who presented the code on class and worked perfectly. Maybe you would like a demostrative video

**Comment by Juan-Carlos-TV** [comment]
Also, the codes are milk-server-A00827629.c and milk-client-A00827629.c . . . server is the example of the lab

**Comment by Juan-Carlos-TV** [comment]
Captura de pantalla 2021-12-04 082522

As you can see it works for me

**Comment by VictorRodriguez** [comment]
thanks , I can see

**Pull request closed without merging**
