### PR TITLE
A00827434_homework_02

### PR DESCRIPTION
**Pull request by ErnestoIRS**

### CODE REVIEW

**Comment by ErnestoIRS** [comment]
De nuevo, perdón por tantos commits. Aun no manejo Git ala perfección. El unico archivo importante es A00827434-homework-02

**Comment by VictorRodriguez** [comment]
@ErnestoIRS  this Pull request does not have any code related to the milk seller, please find the right branch or commit and upload it . This branch has only about Montecarlo Pi calculation

**Comment by VictorRodriguez** [comment]
The commit Add files via upload has a zip file , please include the code instead of zip

**Comment by ErnestoIRS** [comment]
Sorry, I'm on it

**Comment by VictorRodriguez** [comment]
A00827434-homework-02 git:(pullrequest) ✗ ./milkFactory&
[1] 22615
➜  A00827434-homework-02 git:(pullrequest) ✗ Poduct quantity 1000

[1]  + 22615 done       ./milkFactory
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller 1
zsh: no such file or directory: ./seller
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller1
Product delivered: 308
Product left: 692
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller
zsh: no such file or directory: ./seller
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller2
Product delivered: 308
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller1
Product delivered: 308
Product left: 76
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller2
Product delivered: 8
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller1
Product delivered: 8
Product left: 60
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller2
Product delivered: 8
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller1
Product delivered: 8
Product left: 44
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller2
Product delivered: 8
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller2
Product delivered: 8
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller2
Product delivered: 8
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller2
Product delivered: 8
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller2
Product delivered: 8
➜  A00827434-homework-02 git:(pullrequest) ✗ ./seller2
There is no enough product%

Good work 100

**Comment by VictorRodriguez** [comment]
There is no need to resend the PR, i already grade it , is ok thanks

**Comment by ErnestoIRS** [comment]
Thank you !

**Pull request closed without merging**
